sudo: false

language: php

php: 7.2

# cache composer downloads so installing is quicker
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    on_success: change
    on_failure: always
    
stages:
  - style
  - test
  - asset

jobs:
    - stage: Style

      language: php

      php: 7.2

      install:
        - composer install
        - php security-checker.phar security:check composer.lock
        - php php-cs-fixer-v2.phar fix . --rules=@Symfony

deploy:
  provider: heroku
  app: repogit
  api_key:
    secure: "YOUR ENCRYPTED API KEY"