language: php

php:
  - 7.1

before_script:
  - composer install

script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi
  - docker run --rm -v $PWD:/app phpqa/php-cs-fixer fix --show-progress=estimating --verbose .
  - docker run --rm -v $PWD:/app phpqa/security-checker security:check
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/EmailTest

# script:
#   - docker run --rm -v $PWD:/app phpqa/phpcs .
#   - docker run --rm -v $PWD:/app phpqa/security-checker security:check
#   - phpunit
#   - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi

deploy:
  provider: heroku
  api_key:
    secure: h9RsW9ea+efFHqW2zlCyz8O8u4aei+kriTmfSUl56aoP+XYYs0dly+0o3JJYX1B78/JoinCMEaqNBjyNjbz6f1LY3F+ZibVMx9b7m2t/nlrGBs4yDgl+QbOYIemoHRCgoU+4AqJK2lLI3ekdcZqHROd6UqzvR3K/YszncjE26v//SgqiA2J2WGRuv3b5uvcnaC0bd8dMjpBVasyoKgmuURs/r9WZIylh/EKgo5kn9uRL9b17avs1WwC/AHiaD164YKFmbb/mpaa0hQDYjiy+q62z++xsRhP9VL6mynms3EYKwKPzOxEWQpisgUcyL9+rHTvcenmLIVRePu5dt6nNYgHFBGx4yggx2AELQL7ohDafqbKPTR1q/VvTfZlVsMsQG264mmk0TCe1giPaTefr8wlU+7n6UViv9StZv1EEsE5R8gxgopvQ1drHZArjiimZ6b2mm+SsjF1yLeFy+Zd8qRxEUm3XQwmmHhJfqOMo3gSmTSu6d4DbNCYyDopgRzBW84QfSEC4eS/ufsNe/bFEXnKJNaydjbV5OhJMjznBQl79CJEULP+HIkcbsd5z0zsQwpjRljsVQb0Ked0m7fuJa97PL5NDbt90bQpCvWNOr0ChBGXL0pqzb0u+XC/JVV+6VcPgF/2RTTozPRHsDTbAg2Lz5IYZnehpi9nhPXZQr8g=
  app: repogit
  on:
    repo: alexb31/repogit
    branch: feature
notifications:
  email:
    recipients:
    - alexandrebornstein@gmail.com
    on_success: never
    on_failure: always