sudo: false

# cache composer downloads so installing is quicker
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache

stages:
  - style
  - test
  - asset

jobs:
  include:
    - stage: Style

      language: php

      php: 7.0

      install:
        - composer install
        
    - stage: Style

      language: php

      php: 7.1

      install:
        - composer install

notifications:
  email:
    on_success: change
    on_failure: always