sudo: false
language: php
php: 7.2
cache:
  yarn: true
  directories:
  - "$HOME/.composer/cache"
notifications:
  email:
    on_success: change
    on_failure: always
stages:
- style
- test
- asset
jobs:
- stage: Style
  language: php
  php: 7.2
  install:
  - composer install
  - php security-checker.phar security:check composer.lock
  - php php-cs-fixer-v2.phar fix . --rules=@Symfony
deploy:
  provider: heroku
  app: repogit
  api_key:
    secure: h9RsW9ea+efFHqW2zlCyz8O8u4aei+kriTmfSUl56aoP+XYYs0dly+0o3JJYX1B78/JoinCMEaqNBjyNjbz6f1LY3F+ZibVMx9b7m2t/nlrGBs4yDgl+QbOYIemoHRCgoU+4AqJK2lLI3ekdcZqHROd6UqzvR3K/YszncjE26v//SgqiA2J2WGRuv3b5uvcnaC0bd8dMjpBVasyoKgmuURs/r9WZIylh/EKgo5kn9uRL9b17avs1WwC/AHiaD164YKFmbb/mpaa0hQDYjiy+q62z++xsRhP9VL6mynms3EYKwKPzOxEWQpisgUcyL9+rHTvcenmLIVRePu5dt6nNYgHFBGx4yggx2AELQL7ohDafqbKPTR1q/VvTfZlVsMsQG264mmk0TCe1giPaTefr8wlU+7n6UViv9StZv1EEsE5R8gxgopvQ1drHZArjiimZ6b2mm+SsjF1yLeFy+Zd8qRxEUm3XQwmmHhJfqOMo3gSmTSu6d4DbNCYyDopgRzBW84QfSEC4eS/ufsNe/bFEXnKJNaydjbV5OhJMjznBQl79CJEULP+HIkcbsd5z0zsQwpjRljsVQb0Ked0m7fuJa97PL5NDbt90bQpCvWNOr0ChBGXL0pqzb0u+XC/JVV+6VcPgF/2RTTozPRHsDTbAg2Lz5IYZnehpi9nhPXZQr8g=
